---
# Source: r-app/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shiny-r-app-production
  namespace: argo-cd
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  # Add labels to your application object.
  labels:
    name: shiny-r-app-production
spec:
  project: production
  source:
    repoURL: https://github.com/recruiting-tech/infra-argocd-canary-inf.git
    targetRevision: HEAD
    path: base
    helm:
      version: v3
      valueFiles:
        - environments/production/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
